spring.application.name=cloud-backend-project

# PostgreSQL
spring.datasource.url=jdbc:postgresql://${cloud_backend_db}
spring.datasource.username=${cloud_backend_db_username}
spring.datasource.password=${cloud_backend_db_password}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwt.secret=${cloud_jwt_secret_key}
# 24 hours
app.jwt.expiration-ms=86400000

# Base URL for generating short links
app.base-url=${cloud_base_url}